jira_creation_task:
  description: >
    create jira ticket based on the information.
    - execute jira_creation_agent method and do not call jira api by you own the the code to execute.
    - Here is input information about the jira ticket:
      Priority:- {priority}
      Description:- {description}
  expected_output: >
    jiraId and jiraDescription of the jira ticket created.
  agent: jira_creation_agent