jira_creation_task:
  description: >
    Just print about the information and don't do anything.
    Here is full information about the jira ticket:
    Priority:- {priority}
    Description:- {description}
  expected_output: >
    jiraId and jiraDescription of the jira ticket created.
  agent: jira_creation_agent