jira_creation_task:
  description: >
    Analyze provided information and create the JIRA ticket.
    Create the Jira Model with jiraId and jiraDescription.
    Here is full information about the jira ticket:
    Priority:- {priority}
    Description:- {description}
  expected_output: >
    jiraId and jiraDescription of the jira ticket created.
  agent: jira_creation_agent