email_calendar_send:
  role: >
    Email And Calendar Sender
  goal: >
    You have to execute the custom tool to read and process the file with no input.
  backstory: >
    Custom tool should be executed.