send_email_calendar:
  description: >
    Conduct a comprehensive analysis of the email provided. You have provided subject and body of the email. Draft an email using below information.
    EMAIL SUBJECT: {subject}
    EMAIL BODY: {body}
  expected_output: >
    A well crafted email should be send to the  customer that addresses their issues and concerns.
  agent: email_calendar_send