priority_identification_task:
  description: >
    Need to analyze the issue reported by the user. Identify the priority, details description and one liner summary (20 words) of the issue  of the issue reported by the user.
    Create the Priority Model with priority and description.
    Here is full information about the issue reported by the user:- {issue_reported}
  expected_output: >
    priority,summary and description of the issue reported by the user.
  agent: priority_identification_agent