write_email:
  description: >
    You need to write email in a thoughtful and helpful way. The email should be polite and it should show the urgency based on the priority if the issue.
      -  Analyze the information shared to you and need to draft the email.
      -  Email draft should use the html template provided in the FileReadTool. Please do not add summary and description in the table. It should be present in the email body.
      -  Email draft should contain all the html tag present in the html template provided in the FileReadTool.    
      -  subject and body fields should be generated.
    Below are the information that need you can refer and replace in the email template. 
        jira_id:- {jira_id}
        priority:- {priority}
        description:- {description}
        project:- {project}
        summary:- {summary}
        impact:- {impact}
        urgency:- {urgency}
        status_io_id:- {status_io_id}
  expected_output: >
    subject and body of the draft email should be generated based on the information provided in the description.
  agent: email_writer

write_email_no_data:
  description: >
    You need to write email in a thoughtful and helpful way. The email should be polite and it should show the urgency based on the priority if the issue.
      -  Analyze the information shared to you and need to draft the email.
      -  Email draft should use the html template provided in the FileReadTool. Please do not add summary and description in the table. It should be present in the email body.
      -  Email draft should contain all the html tag present in the html template provided in the FileReadTool.    
      -  subject and body fields should be generated.
      -  Do not include any quantitative data such as amount, number of transactions, number customers of etc.
    Below are the information that need you can refer and replace in the email template. 
        jira_id:- {jira_id}
        priority:- {priority}
        description:- {description}
        project:- {project}
        summary:- {summary}
        impact:- {impact}
        urgency:- {urgency}
        status_io_id:- {status_io_id}
  expected_output: >
    subject and body of the draft email should be generated based on the information provided in the description.
  agent: email_writer