priority_analyzer_task:
  description: >
    Extract the information with you in the from of PDF file and analyze the information.
  expected_output: >
    print the impact and priority of the issue reported by user.
  agent: priority_analyzer

priority_identification_task:
  description: >
    Please identify the priority of the given issue with the help of information shared by Priority Analyzer agent.
    Below is the issue shared by user: {issue_reported}
  expected_output: >
    print the priority of the issue reported by user.
  agent: priority_identification