#!/usr/bin/env python
import json
from dataclasses import field
from typing import List

from pydantic import BaseModel
from crewai.flow.flow import Flow, listen, start

from .crews.send_google_no_data_crew.send_google_no_data_crew import GoogleSendNoDataCrew
from .crews.status_page_creation_crew.status_page_creation_crew import  StatusPageCreationCrew
from .types import JiraModel
# from gnoc_automation_flow.src.gnoc_automation_flow.crews.jira_creation_crew.jira_creation_crew import JiraCreationCrew
from .crews.priority_identification_crew.priority_identification_crew import PriorityIdentificationCrew
from .crews.jira_creation_crew.jira_creation_crew import JiraCreationCrew
from .crews.send_google_crew.send_google_crew import GoogleSendCrew
from .crews.google_crew.google_crew import GoogleCrew

class PriorityIdentificationState(BaseModel):
    priority: str = ""
    description: str = ""
    summary: str = ""
    issue_reported: str = ""
    jira_id: str = ""
    subject: str = ""
    # to: list = None
    body: str = ""
    subject1: str = ""
    subject2: str = ""
    body1: str = ""
    body2: str = ""

class PriorityIdentificationFlow(Flow[PriorityIdentificationState]):

    @start()
    def generate_issue_reported_user(self):
        print("Generating issue reported by user")
        self.state.issue_reported = "As a user I am not able to perform the transaction from the last 15 minutes and due to this over 500K transactions have declined that result in the revenue loss of more than 150K US dollar. Please look into this issue on urgent basis."
        # self.state.issue_reported = "As a user I am not able to perform the transaction from the last 5 minutes and due to this around 100 transactions have declined that result in the revenue loss of around 1000 US dollar. Please look into this issue and provide resolution."

    @listen(generate_issue_reported_user)
    def identify_priority_of_issue(self):
        print("Identifying the priority of the issue reported by user.")
        result = (
            PriorityIdentificationCrew()
            .crew()
            .kickoff(inputs={"issue_reported": self.state.issue_reported})
        )

        print(f"Raw result:- {result.raw}")
        print(f"Priority:- {result["priority"]}")
        print(f"Summary:- {result["summary"]}")
        print(f"Description:- {result["description"]}")
        self.state.priority = result["priority"]
        self.state.description = result["description"]
        self.state.summary= result["summary"]

    # @listen(identify_priority_of_issue)
    # def save_issue_and_priority(self):
    #     print("Saving priority")
    #     with open("priority.txt", "w") as f:
    #         f.write("Issue reported by user:-\n" + self.state.issue_reported + "\n\nPriority predicted by LLM:- " + self.state.priority + "\n\nDescription generated by LLM:- " + self.state.description)

    @listen(identify_priority_of_issue)
    def create_jira_ticket(self):
        print("Create Jira Ticket based on the priority and description generated by LLM.")
        print(f"Priority:- {self.state.priority}")
        print(f"Summary:- {self.state.summary}")
        print(f"Description:- {self.state.description}")
        result = (
            JiraCreationCrew()
            .crew()
            .kickoff(inputs={"priority": self.state.priority, "description": self.state.description, "summary": self.state.summary})
        )

        print(f"Jira ticket creation output:- {result.raw}")
        print(f"jiraId:- {result["jira_id"]}")
        print(f"jiraDescription:- {result["description"]}")
        self.state.jira_id = result["jira_id"]
        self.state.priority = result["priority"]
        self.state.description = result["description"]
        self.state.summary = result["summary"]

    @listen(create_jira_ticket)
    def create_status_page_ticket(self):
        print("Create Status Page based on the priority and description generated by LLM.")
        result = (
            StatusPageCreationCrew()
            .crew()
            #.kickoff()
            .kickoff(inputs={"jira_id": self.state.jira_id, "priority": self.state.priority, "description": self.state.description, "summary": self.state.summary})
        )
        print("\n\n################################\n\n")
        print(f"Status Page Creation Output:- {result}")
        print("\n\n################################\n\n")

    @listen(create_status_page_ticket)
    def create_email_template(self):
        print("Creating email template")
        self.state.description = self.state.issue_reported
        result = (
            GoogleCrew()
            .crew()
            .kickoff(inputs={"jira_id": self.state.jira_id, "priority": self.state.priority, "description": self.state.description,
                             "project": "GNOC", "summary": self.state.summary})
        )

        print("result.raw Email template created", result.raw)
        # print("Email subject", result["subject"])
        # print("Email to", result["to"])
        print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
        print("Email body", result["body"])
        print("jira_id", result["jira_id"])
        print("Email summary", result["summary"])
        print("Email subject", result["subject"])
        self.state.jira_id = result["jira_id"]
        self.state.summary = result["summary"]
        self.state.subject = result["subject"]
        self.state.body = result["body"]
        # self.state.subject1 = json.dumps(list(enumerate(result))[3][1][1][0].json_dict["subject"])
        # self.state.body1 = json.dumps(list(enumerate(result))[3][1][1][0].json_dict["body"])

        i = 0
        for task_output in list(enumerate(result))[3][1][1]:
            print("Attributes of TaskOutput object:")
            for attr, value in vars(task_output).items():
                if attr == "pydantic":
                    print(f"{attr}: {value.subject}")
                    print(f"{attr}: {value.body}")
                    if i == 0:
                        self.state.subject1 = value.subject
                        self.state.body1 = value.body
                        i = i + 1
                    else:
                        self.state.subject2 = value.subject
                        self.state.body2 = value.body

        # self.state.subject1 = list(enumerate(result))[3][1][1][0].json_dict["subject"]
        # self.state.body1 = list(enumerate(result))[3][1][1][0].json_dict["body"]
        #
        # self.state.subject2 = list(enumerate(result))[3][1][1][1].json_dict["subject"]
        # self.state.body2 = list(enumerate(result))[3][1][1][1].json_dict["body"]

    @listen(create_email_template)
    def send_email_gmail(self):
        print("Send email and calendar invite")
        print(f"Email subject1:- {self.state.subject1}")
        print(f"Email body1:- {self.state.body1}")
        result = (
            GoogleSendCrew()
            .crew()
            # .kickoff(inputs={"subject": self.state.subject1, "body": self.state.body1, "flag": False})
            .kickoff(inputs={"subject": self.state.subject1, "body": self.state.body1})
        )

        print(f"Email subject2:- {self.state.subject2}")
        print(f"Email body2:- {self.state.body2}")
        self.state.subject2 = self.state.subject2
        self.state.body2 = self.state.body2
        print("result template created", result.raw)

    @listen(send_email_gmail)
    def send_email_no_data_gmail(self):
        print("Send email and calendar invite")
        print(f"send_email_no_data_gmail :: Email subject2:- {self.state.subject2}")
        print(f"send_email_no_data_gmail  :: Email body2:- {self.state.body2}")
        result = (
            GoogleSendNoDataCrew()
            .crew()
            # .kickoff(inputs={"subject": self.state.subject2, "body": self.state.body2, "flag": True})
            .kickoff(inputs={"subject": self.state.subject2, "body": self.state.body2})
        )

        print("result template created", result.raw)


def kickoff():
    priority_identification_flow = PriorityIdentificationFlow()
    priority_identification_flow.kickoff()


def plot():
    priority_identification_flow = PriorityIdentificationFlow()
    priority_identification_flow.plot()


if __name__ == "__main__":
    kickoff()
