send_email_calendar_no_data:
  description: >
    Task to execute the custom tool to read and process the file with no input.
  expected_output: >
    Custom tool should be executed.
  agent: email_calendar_send_no_data